services:
  postgres:
    container_name: postgres

    image: postgres

    ports:
      - '5432:5432'

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: db_movieflix